### PR TITLE
master

### PR DESCRIPTION
**Pull request by guilefranc**
Add REST services monitoring

### CODE REVIEW

**Comment by yesnault** [comment]
Thanks !

Seems missig httpMethod in csv export

**Comment by yesnault** [comment]
Can you replace ModePurge.XML to ModePurge.CONTENT ?

**Comment by yesnault** [comment]
Can you update documentation on https://github.com/soapower/docs/tree/1.4.x (with new screenshots too ?) ? Thks

**Comment by yesnault** [comment]
On service page (new, edit), can you explain de difference between soap and rest and consequences (localTarget start with soap/ or rest/, header http, record of http method, etc... Explain briefly serviceAction...) Thks !

**Comment by yesnault** [comment]
Hi,

There a bug with header of the response for Rest request. Content Type are always : Content-Type: application/xml; charset=utf-8 (see here: https://github.com/soapower/soapower/blob/1.4.x/app/controllers/Rest.scala#L142 )

You can test with SoapUI 5.0.0 (with REST mock) for testing.
Thks !

**Comment by yesnault** [comment]
I have a remote target : GET http://localhost:8080/accountcreation
In request download file, there is http://localhost:8080/accountcreation/accountcreation instead of http://localhost:8080/accountcreation, is it normal ?

**Comment by guilefranc** [comment]
No, it's a bug, it should be http;//localhost:8080/accountcreation

**Comment by guilefranc** [comment]
i am not able to recreate your issue. Can you tell me the URL call you made to soapower ?

**Comment by yesnault** [comment]
Log of Rest.getRemoteTargetWithCall(...) method :

```
[debug] 2014-04-17 19:24:21,622 application - Call : service2/accountcreation
[debug] 2014-04-17 19:24:21,623 application - localTarget : service2
[debug] 2014-04-17 19:24:21,623 application - effectiveCall : [Ljava.lang.String;@4f9a12cf
[debug] 2014-04-17 19:24:21,623 application - remoteTarget : http://localhost:8080/accountcreation
[debug] 2014-04-17 19:24:21,623 application - call.split(localTarget)(1):/accountcreation
```

Service configuration (csv format) : 

```
service;3462;rest;get;service2;service2;http://localhost:8080/accountcreation;60000;true;true;false;yesnault;NoMockGroup
```

**Comment by yesnault** [comment]
The test is done with SoapUI 5.0.0 with included tutorial

**Comment by yesnault** [comment]
Hum, I understood behavior of Soapui...
The good configuration is : 

```
service;3462;rest;get;service2;service2/accountcreation;http://localhost:8080/accountcreation;60000;true;true;false;yesnault;NoMockGroup
```

so, no bug :)

**Comment by yesnault** [comment]
If we choose on search or analysis  page a REST Service Action, the action is not selected in listbox. Example of url : 

```
http://localhost:9000/#/search/all/all/GET%2520service2%252Faccountcreation/yesterday/today/all
```

The action _GET service/accountcreation_ is not selected in listbox

**Comment by yesnault** [comment]
Is it possible to support "multipart/form-data" ?

**Comment by guilefranc** [comment]
Yes it should be possible, I will look at it

**Comment by guilefranc** [comment]
According to Play doc, ScalaWS can't be used for sending multipart/form-data directly (http://www.playframework.com/documentation/2.2.x/ScalaWS).

**Comment by yesnault** [comment]
Could you implement controllers.Rest.autoIndex  ?

**Comment by guilefranc** [comment]
Yes i will look at it

**Pull request merged**
